version: '3.8'

services:
  # MongoDB服务
  mongodb:
    image: mongo:5.0
    container_name: todoing_mongodb_local
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data_local:/data/db
    networks:
      - todoing_network

  # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: todoing_backend_local
    restart: always
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://admin:password@mongodb:27017/todoing?authSource=admin
      JWT_SECRET: your_jwt_secret_here
      PORT: 5000
    ports:
      - "5001:5000"
    depends_on:
      - mongodb
    networks:
      - todoing_network

  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: todoing_frontend_local
    restart: always
    ports:
      - "3002:80"
    depends_on:
      - backend
    networks:
      - todoing_network
    environment:
      - VITE_API_URL=http://host.docker.internal:5001/api

# 数据卷定义
volumes:
  mongodb_data_local:
    driver: local

# 网络定义
networks:
  todoing_network:
    driver: bridge