version: '3.8'

services:
  # MongoDB服务
  mongodb:
    image: mongo:4.4
    container_name: todoing_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - todoing_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: todoing_backend
    restart: always
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/todoing
      - JWT_SECRET=your_jwt_secret_here
      - PORT=5001
      # 是否禁用注册功能
      - DISABLE_REGISTRATION=false
      # 是否启用登录验证码
      - ENABLE_CAPTCHA=false
      # 默认用户配置（示例）
      # - DEFAULT_USERNAME=admin
      # - DEFAULT_EMAIL=admin@example.com
      # - DEFAULT_PASSWORD=securepassword
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    networks:
      - todoing_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: todoing_frontend
    restart: always
    ports:
      - "80:80"
    environment:
      - VITE_API_BASE_URL=/api
      # 是否禁用注册功能
      - VITE_DISABLE_REGISTRATION=false
      # 是否启用登录验证码
      - VITE_ENABLE_CAPTCHA=false
    depends_on:
      - backend
    networks:
      - todoing_network

# 数据卷定义
volumes:
  mongodb_data:

# 网络定义
networks:
  todoing_network:
    driver: bridge