services:
  mongodb:
    image: mongo:7
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
      - todoing_network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/todoing
      - JWT_SECRET=your_jwt_secret_here
      - DISABLE_REGISTRATION=false
      - ENABLE_CAPTCHA=true
      - DEFAULT_USERNAME=admin
      - DEFAULT_EMAIL=admin@example.com
      - DEFAULT_PASSWORD=admin123
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
    networks:
      - todoing_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - TARGETPLATFORM=linux/amd64
    ports:
      - "81:80"
    environment:
      - VITE_API_BASE_URL=/api
      - VITE_DISABLE_REGISTRATION=false
      - VITE_ENABLE_CAPTCHA=true
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - todoing_network

networks:
  todoing_network:
    driver: bridge

volumes:
  mongodb_data: