# TodoIng - Node.js 后端部署方案
# 使用: docker-compose -f docker-compose.nodejs.yml up -d

version: '3.8'

services:
  # MongoDB 数据库
  mongodb:
    image: mongo:7-jammy
    container_name: todoing_mongodb_nodejs
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: todoing
    volumes:
      - mongodb_data_nodejs:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - todoing_nodejs_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis 缓存 (用于会话和验证码)
  redis:
    image: redis:7-alpine
    container_name: todoing_redis_nodejs
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass redis123
    volumes:
      - redis_data_nodejs:/data
    networks:
      - todoing_nodejs_network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Node.js 后端服务
  backend-nodejs:
    image: ${NODEJS_BACKEND_IMAGE:-axiu/todoing:latest}
    build:
      context: ../backend
      dockerfile: Dockerfile
      target: production
    container_name: todoing_backend_nodejs
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      NODE_ENV: production
      PORT: 5001
      MONGO_URI: mongodb://admin:admin123@mongodb:27017/todoing?authSource=admin
      REDIS_URL: redis://:redis123@redis:6379
      JWT_SECRET: ${JWT_SECRET:-your_super_secret_jwt_key_change_in_production}
      
      # 功能开关
      DISABLE_REGISTRATION: ${DISABLE_REGISTRATION:-false}
      ENABLE_CAPTCHA: ${ENABLE_CAPTCHA:-true}
      ENABLE_EMAIL_VERIFICATION: ${ENABLE_EMAIL_VERIFICATION:-false}
      
      # 默认管理员账户
      DEFAULT_USERNAME: ${DEFAULT_USERNAME:-admin}
      DEFAULT_EMAIL: ${DEFAULT_EMAIL:-admin@example.com}
      DEFAULT_PASSWORD: ${DEFAULT_PASSWORD:-admin123}
      
      # 邮件配置
      EMAIL_HOST: ${EMAIL_HOST:-smtp.gmail.com}
      EMAIL_PORT: ${EMAIL_PORT:-587}
      EMAIL_SECURE: ${EMAIL_SECURE:-false}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      
      # 日志配置
      LOG_LEVEL: ${LOG_LEVEL:-info}
      LOG_FORMAT: ${LOG_FORMAT:-combined}
      
    env_file:
      - .env
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./logs/nodejs:/app/logs
    networks:
      - todoing_nodejs_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    container_name: todoing_frontend_nodejs
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      VITE_API_BASE_URL: http://localhost:5001/api
      VITE_DISABLE_REGISTRATION: ${DISABLE_REGISTRATION:-false}
      VITE_ENABLE_CAPTCHA: ${ENABLE_CAPTCHA:-true}
      VITE_APP_NAME: TodoIng
      VITE_APP_VERSION: 1.0.0
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      backend-nodejs:
        condition: service_healthy
    networks:
      - todoing_nodejs_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx 反向代理
  nginx:
    image: nginx:alpine
    container_name: todoing_nginx_nodejs
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nodejs.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - frontend
      - backend-nodejs
    networks:
      - todoing_nodejs_network

networks:
  todoing_nodejs_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  mongodb_data_nodejs:
    driver: local
  redis_data_nodejs:
    driver: local
