// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/captcha": {
            "get": {
                "description": "生成图形验证码用于注册/登录验证",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "生成验证码",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.GenerateCaptchaResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/routes.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "用户登录获取访问令牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "用户登录请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/routes.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/routes.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/routes.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "description": "获取当前认证用户的信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "获取当前用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.GetUserResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/routes.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/routes.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "注册新用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "用户注册请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/routes.RegisterResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/routes.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/routes.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/send-email-code": {
            "post": {
                "description": "发送邮箱验证码用于用户注册验证",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "发送注册邮箱验证码",
                "parameters": [
                    {
                        "description": "发送邮箱验证码请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.SendEmailCodeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.SendEmailCodeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/routes.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/routes.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/send-login-email-code": {
            "post": {
                "description": "发送邮箱验证码用于用户登录验证",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "发送登录邮箱验证码",
                "parameters": [
                    {
                        "description": "发送登录邮箱验证码请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.SendLoginEmailCodeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.SendLoginEmailCodeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/routes.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/routes.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/reports": {
            "get": {
                "description": "获取用户的所有报告",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "获取报告列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "userId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.GetReportsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/routes.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/routes.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/reports/export": {
            "post": {
                "description": "导出报告为指定格式",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "导出报告",
                "parameters": [
                    {
                        "description": "导出报告请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.ExportReportRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.ExportReportResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/routes.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/routes.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/reports/generate": {
            "post": {
                "description": "根据类型和周期生成报告",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "生成报告",
                "parameters": [
                    {
                        "description": "生成报告请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.GenerateReportRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.GenerateReportResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/routes.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/routes.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/reports/polish": {
            "post": {
                "description": "使用AI润色报告内容",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "润色报告",
                "parameters": [
                    {
                        "description": "润色报告请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.PolishReportRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.PolishReportResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/routes.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/routes.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/reports/{id}": {
            "get": {
                "description": "根据ID获取报告详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "获取单个报告",
                "parameters": [
                    {
                        "type": "string",
                        "description": "报告ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.GetReportResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/routes.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/routes.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/routes.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "根据ID删除报告",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "删除报告",
                "parameters": [
                    {
                        "type": "string",
                        "description": "报告ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.DeleteReportResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/routes.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/routes.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/routes.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tasks": {
            "get": {
                "description": "获取用户的所有任务",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "获取任务列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "userId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.GetTasksResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/routes.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/routes.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "创建一个新的任务",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "创建任务",
                "parameters": [
                    {
                        "description": "创建任务请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.CreateTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/routes.CreateTaskResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/routes.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/routes.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tasks/{id}": {
            "get": {
                "description": "根据ID获取任务详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "获取单个任务",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.GetTaskResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/routes.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/routes.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/routes.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "更新任务信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "更新任务",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新任务请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.UpdateTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.UpdateTaskResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/routes.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/routes.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/routes.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "根据ID删除任务",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "删除任务",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.DeleteTaskResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/routes.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/routes.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/routes.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tasks/{id}/assign": {
            "post": {
                "description": "将任务分配给用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "分配任务",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "分配任务请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.UpdateTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.UpdateTaskResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/routes.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/routes.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/routes.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tasks/{id}/comments": {
            "post": {
                "description": "为任务添加评论",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "添加评论",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "添加评论请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.AddCommentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.AddCommentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/routes.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/routes.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/routes.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "routes.AddCommentRequest": {
            "type": "object",
            "properties": {
                "task_id": {
                    "description": "任务ID",
                    "type": "string"
                },
                "text": {
                    "description": "评论内容",
                    "type": "string"
                },
                "token": {
                    "description": "Token",
                    "type": "string"
                }
            }
        },
        "routes.AddCommentResponse": {
            "type": "object",
            "properties": {
                "comment": {
                    "description": "评论信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/routes.Comment"
                        }
                    ]
                },
                "message": {
                    "description": "消息",
                    "type": "string"
                }
            }
        },
        "routes.Comment": {
            "type": "object",
            "properties": {
                "created_by": {
                    "description": "创建者",
                    "type": "string"
                },
                "id": {
                    "description": "评论ID",
                    "type": "string"
                },
                "text": {
                    "description": "评论内容",
                    "type": "string"
                }
            }
        },
        "routes.CreateTaskRequest": {
            "type": "object",
            "properties": {
                "assignee": {
                    "description": "分配给",
                    "type": "string"
                },
                "description": {
                    "description": "任务描述",
                    "type": "string"
                },
                "priority": {
                    "description": "任务优先级",
                    "type": "integer"
                },
                "status": {
                    "description": "任务状态",
                    "type": "integer"
                },
                "title": {
                    "description": "任务标题",
                    "type": "string"
                },
                "token": {
                    "description": "Token",
                    "type": "string"
                }
            }
        },
        "routes.CreateTaskResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "消息",
                    "type": "string"
                },
                "task": {
                    "description": "任务信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/routes.Task"
                        }
                    ]
                }
            }
        },
        "routes.DeleteReportResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "消息",
                    "type": "string"
                }
            }
        },
        "routes.DeleteTaskResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "消息",
                    "type": "string"
                }
            }
        },
        "routes.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "错误信息",
                    "type": "string"
                }
            }
        },
        "routes.ExportReportRequest": {
            "type": "object",
            "properties": {
                "format": {
                    "description": "格式",
                    "type": "string"
                },
                "id": {
                    "description": "报告ID",
                    "type": "string"
                },
                "token": {
                    "description": "Token",
                    "type": "string"
                }
            }
        },
        "routes.ExportReportResponse": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "内容",
                    "type": "string"
                },
                "filename": {
                    "description": "文件名",
                    "type": "string"
                },
                "message": {
                    "description": "消息",
                    "type": "string"
                }
            }
        },
        "routes.GenerateCaptchaResponse": {
            "type": "object",
            "properties": {
                "captcha": {
                    "description": "验证码",
                    "type": "integer"
                },
                "message": {
                    "description": "消息",
                    "type": "string"
                }
            }
        },
        "routes.GenerateReportRequest": {
            "type": "object",
            "properties": {
                "end_date": {
                    "description": "结束日期",
                    "type": "string"
                },
                "period": {
                    "description": "周期",
                    "type": "string"
                },
                "start_date": {
                    "description": "开始日期",
                    "type": "string"
                },
                "token": {
                    "description": "Token",
                    "type": "string"
                },
                "type": {
                    "description": "报告类型",
                    "type": "integer"
                }
            }
        },
        "routes.GenerateReportResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "消息",
                    "type": "string"
                },
                "report": {
                    "description": "报告信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/routes.Report"
                        }
                    ]
                }
            }
        },
        "routes.GetReportResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "消息",
                    "type": "string"
                },
                "report": {
                    "description": "报告信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/routes.Report"
                        }
                    ]
                }
            }
        },
        "routes.GetReportsResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "消息",
                    "type": "string"
                },
                "reports": {
                    "description": "报告列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/routes.Report"
                    }
                }
            }
        },
        "routes.GetTaskResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "消息",
                    "type": "string"
                },
                "task": {
                    "description": "任务信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/routes.Task"
                        }
                    ]
                }
            }
        },
        "routes.GetTasksResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "消息",
                    "type": "string"
                },
                "tasks": {
                    "description": "任务列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/routes.Task"
                    }
                }
            }
        },
        "routes.GetUserResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "消息",
                    "type": "string"
                },
                "user": {
                    "description": "用户信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/routes.User"
                        }
                    ]
                }
            }
        },
        "routes.LoginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "邮箱地址",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                }
            }
        },
        "routes.LoginResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "消息",
                    "type": "string"
                },
                "token": {
                    "description": "JWT token",
                    "type": "string"
                },
                "user": {
                    "description": "用户信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/routes.User"
                        }
                    ]
                }
            }
        },
        "routes.PolishReportRequest": {
            "type": "object",
            "properties": {
                "api_key": {
                    "description": "API密钥",
                    "type": "string"
                },
                "api_url": {
                    "description": "API URL",
                    "type": "string"
                },
                "model": {
                    "description": "模型",
                    "type": "string"
                },
                "provider": {
                    "description": "提供商",
                    "type": "string"
                },
                "report_id": {
                    "description": "报告ID",
                    "type": "string"
                },
                "token": {
                    "description": "Token",
                    "type": "string"
                }
            }
        },
        "routes.PolishReportResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "消息",
                    "type": "string"
                },
                "report": {
                    "description": "报告信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/routes.Report"
                        }
                    ]
                }
            }
        },
        "routes.RegisterRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "邮箱地址",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "routes.RegisterResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "消息",
                    "type": "string"
                },
                "token": {
                    "description": "JWT token",
                    "type": "string"
                },
                "user": {
                    "description": "用户信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/routes.User"
                        }
                    ]
                }
            }
        },
        "routes.Report": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "内容",
                    "type": "string"
                },
                "id": {
                    "description": "报告ID",
                    "type": "string"
                },
                "period": {
                    "description": "周期",
                    "type": "string"
                },
                "polished_content": {
                    "description": "润色后的内容",
                    "type": "string"
                },
                "statistics": {
                    "description": "统计信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/routes.ReportStatistics"
                        }
                    ]
                },
                "tasks": {
                    "description": "任务列表",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "description": "标题",
                    "type": "string"
                },
                "type": {
                    "description": "报告类型",
                    "type": "integer"
                },
                "user_id": {
                    "description": "用户ID",
                    "type": "string"
                }
            }
        },
        "routes.ReportStatistics": {
            "type": "object",
            "properties": {
                "completed_tasks": {
                    "description": "完成任务数",
                    "type": "integer"
                },
                "completion_rate": {
                    "description": "完成率",
                    "type": "integer"
                },
                "in_progress_tasks": {
                    "description": "进行中任务数",
                    "type": "integer"
                },
                "overdue_tasks": {
                    "description": "逾期任务数",
                    "type": "integer"
                },
                "total_tasks": {
                    "description": "总任务数",
                    "type": "integer"
                }
            }
        },
        "routes.SendEmailCodeRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "邮箱地址",
                    "type": "string"
                }
            }
        },
        "routes.SendEmailCodeResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "ID",
                    "type": "string"
                },
                "message": {
                    "description": "消息",
                    "type": "string"
                }
            }
        },
        "routes.SendLoginEmailCodeRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "邮箱地址",
                    "type": "string"
                }
            }
        },
        "routes.SendLoginEmailCodeResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "ID",
                    "type": "string"
                },
                "message": {
                    "description": "消息",
                    "type": "string"
                }
            }
        },
        "routes.Task": {
            "type": "object",
            "properties": {
                "assignee": {
                    "description": "分配给",
                    "type": "string"
                },
                "created_by": {
                    "description": "创建者",
                    "type": "string"
                },
                "description": {
                    "description": "任务描述",
                    "type": "string"
                },
                "id": {
                    "description": "任务ID",
                    "type": "string"
                },
                "priority": {
                    "description": "任务优先级",
                    "type": "integer"
                },
                "status": {
                    "description": "任务状态",
                    "type": "integer"
                },
                "title": {
                    "description": "任务标题",
                    "type": "string"
                }
            }
        },
        "routes.UpdateTaskRequest": {
            "type": "object",
            "properties": {
                "assignee": {
                    "description": "分配给",
                    "type": "string"
                },
                "description": {
                    "description": "任务描述",
                    "type": "string"
                },
                "id": {
                    "description": "任务ID",
                    "type": "string"
                },
                "priority": {
                    "description": "任务优先级",
                    "type": "integer"
                },
                "status": {
                    "description": "任务状态",
                    "type": "integer"
                },
                "title": {
                    "description": "任务标题",
                    "type": "string"
                },
                "token": {
                    "description": "Token",
                    "type": "string"
                }
            }
        },
        "routes.UpdateTaskResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "消息",
                    "type": "string"
                },
                "task": {
                    "description": "任务信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/routes.Task"
                        }
                    ]
                }
            }
        },
        "routes.User": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "邮箱地址",
                    "type": "string"
                },
                "id": {
                    "description": "用户ID",
                    "type": "string"
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:5001",
	BasePath:         "/api",
	Schemes:          []string{"http"},
	Title:            "TodoIng API",
	Description:      "TodoIng task management system API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
