name: Docker Multi-Architecture Build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component:
          - name: "nodejs-backend"
            image: "axiu/todoing"
            context: "./backend"
            dockerfile: "Dockerfile"
          - name: "golang-backend"
            image: "axiu/todoing-go"
            context: "./backend-go"
            dockerfile: "Dockerfile"
          - name: "frontend"
            image: "axiu/todoing-frontend"
            context: "./frontend"
            dockerfile: "Dockerfile"
    
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Extract metadata (tags, labels) for ${{ matrix.component.name }}
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.component.image }}
          tags: |
            type=ref,event=tag
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value={{date 'YYYYMMDD'}}-{{sha}}
      -
        name: Build and push ${{ matrix.component.name }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.component.context }}
          file: ${{ matrix.component.context }}/${{ matrix.component.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max